// Code generated by go generate; DO NOT EDIT.
package volumes

import (
	"net/url"

	"go.podman.io/podman/v6/pkg/bindings/internal/util"
)

// Changed returns true if named field has been set
func (o *RenameOptions) Changed(fieldName string) bool {
	return util.Changed(o, fieldName)
}

// ToParams formats struct fields to be passed to API service
func (o *RenameOptions) ToParams() (url.Values, error) {
	return util.ToParams(o)
}

// WithNewName set field NewName to given value
func (o *RenameOptions) WithNewName(value string) *RenameOptions {
	o.NewName = &value
	return o
}

// GetNewName returns value of field NewName
func (o *RenameOptions) GetNewName() string {
	if o.NewName == nil {
		var z string
		return z
	}
	return *o.NewName
}
