---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: podman.spec
upstream_tag_template: v{version}

jobs:
  - &copr
    job: copr_build
    # Run on every PR
    trigger: pull_request
    owner: rhcontainerbot
    project: packit-builds
    enable_net: true
    targets:
      - centos-stream-9-aarch64
      - centos-stream-9-x86_64
      - centos-stream-8-aarch64
      - centos-stream-8-x86_64
    srpm_build_deps:
      - make
      - rpkg
    actions:
      post-upstream-clone:
        - "rpkg spec --outdir ./"
