---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

downstream_package_name: podman
upstream_tag_template: v{version}

srpm_build_deps:
  - git-archive-all
  - make

actions:
  post-upstream-clone: "curl -O https://gitlab.com/redhat/centos-stream/rpms/podman/-/raw/c10s/podman.spec"

specfile_path: podman.spec

jobs:
  - job: copr_build
    trigger: pull_request
    notifications: &packit_build_failure_notification
      failure_comment:
        message: "Ephemeral COPR build failed. @containers/packit-build please check."
    enable_net: true
    targets:
      - epel-10-x86_64
      - epel-10-aarch64

  # Tests for RHEL
  - job: tests
    trigger: pull_request
    use_internal_tf: true
    notifications: &packit_test_failure_notification
      failure_comment:
        message: "Tests failed. @containers/packit-build please check."
    targets:
      epel-10-x86_64:
        distros: [RHEL-10-Nightly]
      epel-10-aarch64:
        distros: [RHEL-10-Nightly]
    tf_extra_params:
      environments:
        - artifacts:
          - type: repository-file
            id: https://src.fedoraproject.org/rpms/epel-release/raw/epel$releasever/f/epel.repo
