# See the documentation for more information:
# https://packit.dev/docs/configuration/

upstream_package_name: podman
downstream_package_name: podman

actions:
  post-upstream-clone:
    - "curl -O https://src.fedoraproject.org/rpms/podman/raw/main/f/podman.spec"
  fix-spec-file:
    - bash .packit.sh

jobs:
  - job: production_build
    trigger: pull_request
    targets: &production_dist_targets
      - fedora-36
      - fedora-37
      - fedora-rawhide
    scratch: true
