---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

# Build targets can be found at:
# https://copr.fedorainfracloud.org/coprs/rhcontainerbot/packit-builds/

specfile_path: rpm/podman.spec
upstream_tag_template: v{version}

jobs:
  - &copr
    job: copr_build
    trigger: pull_request
    owner: rhcontainerbot
    project: packit-builds
    enable_net: true
    srpm_build_deps:
      - make
    targets:
      - centos-stream-9-aarch64
      - centos-stream-9-x86_64
      - centos-stream-8-aarch64
      - centos-stream-8-x86_64
