---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

# Build targets can be found at:
# https://copr.fedorainfracloud.org/coprs/rhcontainerbot/packit-builds/

specfile_path: rpm/podman.spec
upstream_tag_template: v{version}

jobs:
  - &copr
    job: copr_build
    trigger: pull_request
    owner: rhcontainerbot
    project: packit-builds
    enable_net: true
    srpm_build_deps:
      - make
      - rpkg
    actions:
      fix-spec-file:
        - "bash .packit.sh"

  - <<: *copr
    # Run on commit to main branch
    trigger: commit
    branch: main
    project: podman-next

  - job: propose_downstream
    trigger: release
    update_release: false
    dist_git_branches:
      - fedora-all
    #TODO use the right action to update the goimports
    # For whatever reason, none of the actions seem to work
    #actions:
    #    create-patches:
    #      - "cd rpm && bash update-spec-provides.sh"

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched # rawhide updates are created automatically
