---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/podman.spec
upstream_tag_template: v{version}

srpm_build_deps:
  - make

jobs:
  - job: copr_build
    trigger: pull_request
    enable_net: true
    # keep in sync with https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next
    targets:
      - fedora-all-x86_64
      - fedora-all-aarch64
      - centos-stream+epel-next-8-x86_64
      - centos-stream+epel-next-8-aarch64
      - centos-stream+epel-next-9-x86_64
      - centos-stream+epel-next-9-aarch64
    additional_repos:
      - "copr://rhcontainerbot/podman-next"

  # Run on commit to main branch
  - job: copr_build
    trigger: commit
    branch: main
    owner: rhcontainerbot
    project: podman-next
    enable_net: true

  - job: tests
    identifier: cockpit-revdeps
    trigger: pull_request
    targets:
      - fedora-all
    tf_extra_params:
      environments:
        - artifacts:
          - type: repository-file
            id: https://copr.fedorainfracloud.org/coprs/g/cockpit/main-builds/repo/fedora-$releasever/group_cockpit-main-builds-fedora-$releasever.repo
          - type: repository-file
            id: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/repo/fedora-$releasever/rhcontainerbot-podman-next-fedora-$releasever.repo
          tmt:
            context:
              revdeps: "yes"

  - job: propose_downstream
    trigger: release
    update_release: false
    dist_git_branches:
      - fedora-all

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched # rawhide updates are created automatically
