// Code generated by go generate; DO NOT EDIT.
package autoupdate

import (
	"net/url"

	"github.com/containers/podman/v6/pkg/bindings/internal/util"
)

// Changed returns true if named field has been set
func (o *AutoUpdateOptions) Changed(fieldName string) bool {
	return util.Changed(o, fieldName)
}

// ToParams formats struct fields to be passed to API service
func (o *AutoUpdateOptions) ToParams() (url.Values, error) {
	return util.ToParams(o)
}

// WithAuthfile set field Authfile to given value
func (o *AutoUpdateOptions) WithAuthfile(value string) *AutoUpdateOptions {
	o.Authfile = &value
	return o
}

// GetAuthfile returns value of field Authfile
func (o *AutoUpdateOptions) GetAuthfile() string {
	if o.Authfile == nil {
		var z string
		return z
	}
	return *o.Authfile
}

// WithDryRun set field DryRun to given value
func (o *AutoUpdateOptions) WithDryRun(value bool) *AutoUpdateOptions {
	o.DryRun = &value
	return o
}

// GetDryRun returns value of field DryRun
func (o *AutoUpdateOptions) GetDryRun() bool {
	if o.DryRun == nil {
		var z bool
		return z
	}
	return *o.DryRun
}

// WithRollback set field Rollback to given value
func (o *AutoUpdateOptions) WithRollback(value bool) *AutoUpdateOptions {
	o.Rollback = &value
	return o
}

// GetRollback returns value of field Rollback
func (o *AutoUpdateOptions) GetRollback() bool {
	if o.Rollback == nil {
		var z bool
		return z
	}
	return *o.Rollback
}

// WithInsecureSkipTLSVerify set field InsecureSkipTLSVerify to given value
func (o *AutoUpdateOptions) WithInsecureSkipTLSVerify(value bool) *AutoUpdateOptions {
	o.InsecureSkipTLSVerify = &value
	return o
}

// GetInsecureSkipTLSVerify returns value of field InsecureSkipTLSVerify
func (o *AutoUpdateOptions) GetInsecureSkipTLSVerify() bool {
	if o.InsecureSkipTLSVerify == nil {
		var z bool
		return z
	}
	return *o.InsecureSkipTLSVerify
}
