// Code generated by go generate; DO NOT EDIT.
package artifacts

import (
	"net/url"

	"github.com/containers/podman/v5/pkg/bindings/internal/util"
)

// Changed returns true if named field has been set
func (o *PushOptions) Changed(fieldName string) bool {
	return util.Changed(o, fieldName)
}

// ToParams formats struct fields to be passed to API service
func (o *PushOptions) ToParams() (url.Values, error) {
	return util.ToParams(o)
}

// WithAuthfile set field Authfile to given value
func (o *PushOptions) WithAuthfile(value string) *PushOptions {
	o.Authfile = &value
	return o
}

// GetAuthfile returns value of field Authfile
func (o *PushOptions) GetAuthfile() string {
	if o.Authfile == nil {
		var z string
		return z
	}
	return *o.Authfile
}

// WithPassword set field Password to given value
func (o *PushOptions) WithPassword(value string) *PushOptions {
	o.Password = &value
	return o
}

// GetPassword returns value of field Password
func (o *PushOptions) GetPassword() string {
	if o.Password == nil {
		var z string
		return z
	}
	return *o.Password
}

// WithQuiet set field Quiet to given value
func (o *PushOptions) WithQuiet(value bool) *PushOptions {
	o.Quiet = &value
	return o
}

// GetQuiet returns value of field Quiet
func (o *PushOptions) GetQuiet() bool {
	if o.Quiet == nil {
		var z bool
		return z
	}
	return *o.Quiet
}

// WithRetry set field Retry to given value
func (o *PushOptions) WithRetry(value uint) *PushOptions {
	o.Retry = &value
	return o
}

// GetRetry returns value of field Retry
func (o *PushOptions) GetRetry() uint {
	if o.Retry == nil {
		var z uint
		return z
	}
	return *o.Retry
}

// WithRetryDelay set field RetryDelay to given value
func (o *PushOptions) WithRetryDelay(value string) *PushOptions {
	o.RetryDelay = &value
	return o
}

// GetRetryDelay returns value of field RetryDelay
func (o *PushOptions) GetRetryDelay() string {
	if o.RetryDelay == nil {
		var z string
		return z
	}
	return *o.RetryDelay
}

// WithTlsVerify set field TlsVerify to given value
func (o *PushOptions) WithTlsVerify(value bool) *PushOptions {
	o.TlsVerify = &value
	return o
}

// GetTlsVerify returns value of field TlsVerify
func (o *PushOptions) GetTlsVerify() bool {
	if o.TlsVerify == nil {
		var z bool
		return z
	}
	return *o.TlsVerify
}

// WithUsername set field Username to given value
func (o *PushOptions) WithUsername(value string) *PushOptions {
	o.Username = &value
	return o
}

// GetUsername returns value of field Username
func (o *PushOptions) GetUsername() string {
	if o.Username == nil {
		var z string
		return z
	}
	return *o.Username
}
