#!/bin/bash

set -e
source $(dirname $0)/lib.sh

req_env_var "
OS_RELEASE_ID $OS_RELEASE_ID
CNI_COMMIT $CNI_COMMIT
CRIO_COMMIT $CRIO_COMMIT
CRIU_COMMIT $CRIU_COMMIT
RUNC_COMMIT $RUNC_COMMIT
FEDORA_CNI_COMMIT $FEDORA_CNI_COMMIT

PACKER_BUILDS $PACKER_BUILDS

CENTOS_BASE_IMAGE $CENTOS_BASE_IMAGE
UBUNTU_BASE_IMAGE $UBUNTU_BASE_IMAGE
RHEL_BASE_IMAGE $RHEL_BASE_IMAGE
FEDORA_IMAGE_PREFIX $FEDORA_IMAGE_PREFIX
FEDORA_IMAGE_URL $FEDORA_IMAGE_URL
FEDORA_CSUM_URL $FEDORA_CSUM_URL
FAH_IMAGE_PREFIX $FAH_IMAGE_PREFIX
FAH_IMAGE_URL $FAH_IMAGE_URL
FAH_CSUM_URL $FAH_CSUM_URL

RHSM_COMMAND $RHSM_COMMAND
BUILT_IMAGE_SUFFIX $BUILT_IMAGE_SUFFIX
SERVICE_ACCOUNT $SERVICE_ACCOUNT
GCE_SSH_USERNAME $GCE_SSH_USERNAME
GCP_PROJECT_ID $GCP_PROJECT_ID
PACKER_VER $PACKER_VER
SCRIPT_BASE $SCRIPT_BASE
PACKER_BASE $PACKER_BASE
"

# TODO: Skip building images if $CIRRUS_BRANCH =~ "master" and
# commit message of $CIRRUS_CHANGE_IN_REPO contains a magic word
# produced by 'commit_and_create_upstream_pr.sh' script (see .cirrus.yml)

show_env_vars

# Fedora and FAH need cloud-init w/ ssh keys
nocloud_floppy /tmp/cidata_$CIRRUS_BUILD_ID
export CIDATA_IMAGE=/tmp/cidata_$CIRRUS_BUILD_ID.img
export CIDATA_SSH_KEY=/tmp/cidata_$CIRRUS_BUILD_ID.ssh

cd "$GOSRC/$PACKER_BASE"
make PACKER_VER=$PACKER_VER PACKER_BUILDS=$PACKER_BUILDS

# TODO: Report back to PR names of built images
