FROM quay.io/fedora/fedora-coreos:stable

# Setup the podman-next copr repo
# The source file for the dnf repo may say `rawhide` but it's release
# agnostic and `rawhide` in the name is unlikely to change compared
# with URLs containing fedora release numbers.
ADD https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/repo/fedora-rawhide/rhcontainerbot-podman-next-fedora-rawhide.repos /etc/yum.repos.d/rhcontainerbot-podman-next-fedora.repo
ADD https://download.copr.fedorainfracloud.org/results/rhcontainerbot/podman-next/pubkey.gpg /etc/pki/rpm-gpg/rhcontainerbot-podman-next-fedora.gpg

# Replace aardvark-dns, containers-common[-extra], crun, netavark, podman
# Install crun-wasm and wasmedge-rt
# Remove moby-engine, containerd, runc
# Note: Currently does not result in a size reduction for the container image
RUN rpm-ostree override replace --experimental --freeze \
    --from repo="copr:copr.fedorainfracloud.org:rhcontainerbot:podman-next" \
    aardvark-dns containers-common containers-common-extra crun crun-wasm netavark podman && \
    rpm-ostree install wasmedge-rt && \
    rpm-ostree override remove moby-engine containerd runc && \
    ostree container commit

LABEL quay.expires-after=30d
