name: podman # you probably want to 'snapcraft register <name>'
version: '0.11.1.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Manage pods, containers and container images
description: |
  `podman` is a tool for managing Pods, Containers, and Container Images
  in multiple formats including Docker/OSI images. It exposes the same
  command line interface as Docker, but runs containers unprivileged by
  default.

confinement: devmode # use 'strict' once you have the right plugs and slots

base: core18

parts:
  podman:
    plugin: go
    source: https://github.com/containers/podman/archive/v0.11.1.1.tar.gz
    go-importpath: github.com/containers/podman
    build-packages:
     # https://podman.io/getting-started/installation#build-and-run-dependencies
     - btrfs-tools
     - git
     - golang-go
     - go-md2man
     - iptables
     - libassuan-dev
     - libdevmapper-dev
     - libglib2.0-dev
     - libc6-dev
     - libgpgme11-dev
     - libgpg-error-dev
     - libostree-dev
     - libprotobuf-dev
     - libprotobuf-c0-dev
     - libseccomp-dev
     - libselinux1-dev
     - pkg-config
    stage-packages:
     - libarchive13
     - libassuan0
     - libgpgme11
     - libicu60
     - libostree-1-1
     - libsoup2.4-1
     - libxml2
