# stable/manual/Containerfile
#
# Build a Podman container image from the latest
# stable version of Podman on the Fedora Updates System.
# https://bodhi.fedoraproject.org/updates/?search=podman
# This image can be used to create a secured container
# that runs safely with privileges within the container.
# This Containerfile builds version 1.7.0, the version and
# the RPM name would need to be adjusted before a run as
# appropriate.
#
# To use, first copy an rpm file from bodhi to `/root/tmp`
# and then run:
#   'podman build -f ./Containerfile -t quay.io/podman/stable:v1.7.0 .'
#
# Once complete run:
#   `podman push quay.io/stable:v1.7.0 docker://quay.io/podman/stable:v1.7.0`
#
# Start Build Process using the latest Fedora
FROM registry.fedoraproject.org/fedora:latest

# Don't include container-selinux and remove
# directories used by dnf that are just taking
# up space.
#
COPY /tmp/podman-1.7.0-3.fc30.x86_64.rpm /tmp
RUN yum -y install /tmp/podman-1.7.0-3.fc30.x86_64.rpm fuse-overlayfs --exclude container-selinux; rm -rf /var/cache /var/log/dnf* /var/log/yum.* /tmp/podman*.rpm

ADD https://raw.githubusercontent.com/containers/libpod/master/contrib/podmanimage/stable/containers.conf /etc/containers/

# chmod containers.conf and adjust storage.conf to enable Fuse storage.
RUN chmod 644 /etc/containers/containers.conf; sed -i -e 's|^#mount_program|mount_program|g' -e '/additionalimage.*/a "/var/lib/shared",' -e 's|^mountopt[[:space:]]*=.*$|mountopt = "nodev,fsync=0"|g' /etc/containers/storage.conf
RUN mkdir -p /var/lib/shared/overlay-images /var/lib/shared/overlay-layers /var/lib/shared/vfs-images /var/lib/shared/vfs-layers; touch /var/lib/shared/overlay-images/images.lock; touch /var/lib/shared/overlay-layers/layers.lock; touch /var/lib/shared/vfs-images/images.lock; touch /var/lib/shared/vfs-layers/layers.lock


ENV _CONTAINERS_USERNS_CONFIGURED=""
