# stable/manual/Containerfile
#
# Build a Podman container image from the latest
# stable version of Podman on the Fedora Updates System.
# https://bodhi.fedoraproject.org/updates/?search=podman
# This image can be used to create a secured container
# that runs safely with privileges within the container.
# This Containerfile builds version 1.7.0, the version and
# the RPM name would need to be adjusted before a run as
# appropriate.
#
# To use, first copy an rpm file from bohdi to `/root/tmp`
# and then run:
#   'podman build -f ./Containerfile -t quay.io/podman/stable:v1.7.0 .'
#
# Once complete run:
#   `podman push quay.io/stable:v1.7.0 docker://quay.io/podman/stable:v1.7.0`
#
# Start Build Process using the latest Fedora
FROM fedora:latest

# Don't include container-selinux and remove
# directories used by dnf that are just taking
# up space.
#
COPY /tmp/podman-1.7.0-3.fc30.x86_64.rpm /tmp
RUN yum -y install /tmp/podman-1.7.0-3.fc30.x86_64.rpm fuse-overlayfs --exclude container-selinux; rm -rf /var/cache /var/log/dnf* /var/log/yum.* /tmp/podman*.rpm

# Adjust storage.conf to enable Fuse storage.
RUN sed -i -e 's|^#mount_program|mount_program|g' -e '/additionalimage.*/a "/var/lib/shared",' /etc/containers/storage.conf
RUN mkdir -p /var/lib/shared/overlay-images /var/lib/shared/overlay-layers; touch /var/lib/shared/overlay-images/images.lock; touch /var/lib/shared/overlay-layers/layers.lock

# Adjust libpod.conf to write logging to a file
RUN sed -i 's/events_logger = "journald"/events_logger = "file"/g' /usr/share/containers/libpod.conf; mkdir -p /run/systemd/journal

# Set up environment variables to note that this is
# not starting with usernamespace and default to
# isolate the filesystem with chroot.
ENV _BUILDAH_STARTED_IN_USERNS="" BUILDAH_ISOLATION=chroot
