FROM golang:1.15-alpine AS build-img
COPY ./test/testvol/ /go/src/github.com/containers/podman/cmd/testvol/
COPY ./vendor /go/src/github.com/containers/podman/vendor/
WORKDIR /go/src/github.com/containers/podman
RUN go build -o /testvol ./cmd/testvol

FROM alpine
COPY --from=build-img /testvol /usr/local/bin
WORKDIR /
ENTRYPOINT ["/usr/local/bin/testvol"]
