#!/bin/bash

set -e

echo "/opt/podman/bin" > /etc/paths.d/podman-pkg

ln -s /opt/podman/bin/podman-mac-helper /opt/podman/qemu/bin/podman-mac-helper
ln -s /opt/podman/bin/gvproxy /opt/podman/qemu/bin/gvproxy

# make sure to ignore errors, this is not a hard requirement to use podman
/opt/podman/bin/podman-mac-helper install || :
