#!/bin/bash

set -e

echo "/opt/podman/bin" > /etc/paths.d/podman-pkg

# make sure to ignore errors, this is not a hard requirement to use podman
/opt/podman/bin/podman-mac-helper install || :

# Add pointer to podman docs in manpath
mkdir -p /usr/local/etc/man.d/
echo "MANPATH /opt/podman/docs/man" > /usr/local/etc/man.d/podman.man.conf
