#!/bin/bash
#
# pr-should-include-tests - check that a PR touches tests, or only "safe" files
#
# Reads:
#   BASE_SHA   SHA of the PR base commit
#   HEAD_SHA   SHA of the PR head commit
#   OVERRIDE   "true" if the override label is set, else anything else
#

set -e

ME=$(basename "$0")

# GitHub label which allows overriding this check
OVERRIDE_LABEL="No New Tests"

head=${HEAD_SHA:-HEAD}
if [[ -n "${BASE_SHA:-}" ]]; then
    base=$BASE_SHA
else
    base=$(git merge-base "${DEST_BRANCH:-main}" "$head")
fi

# This gives us a list of files touched in all commits, e.g.
#    A    foo.c
#    M    bar.c
# We look for Added or Modified (not Deleted!) files under 'test'.
# --no-renames ensures that renamed tests (#9420) show up as 'A'dded.
if git diff --name-status --no-renames "$base" "$head" | grep -E -q '^[AM]\s+(test/|.*_test\.go)'; then
    exit 0
fi

# Nothing changed under test subdirectory.
#
# This is OK if the only files being touched are "safe" ones.
filtered_changes=$(git diff --name-only "$base" "$head"     |
                       grep -F -vx .cirrus.yml             |
                       grep -F -vx .pre-commit-config.yaml |
                       grep -F -vx .gitignore              |
                       grep -F -vx go.mod                  |
                       grep -F -vx go.sum                  |
                       grep -F -vx podman.spec.rpkg        |
                       grep -F -vx .golangci.yml           |
                       grep -F -vx winmake.ps1             |
                       grep -E -v  '/*Makefile$'           |
                       grep -E -v  '^[^/]+\.md$'           |
                       grep -E -v  '^.github'              |
                       grep -E -v  '^contrib/'             |
                       grep -E -v  '^docs/'                |
                       grep -E -v  '^hack/'                |
                       grep -E -v  '^nix/'                 |
                       grep -E -v  '^vendor/'              |
                       grep -E -v  '^version/' || true)
if [[ -z "$filtered_changes" ]]; then
    exit 0
fi

# Real code changed without tests. Allow only if the override label is set.
if [[ "${OVERRIDE:-false}" == "true" ]]; then
    exit 0
fi

cat <<EOF
$ME: PR does not include changes in the 'tests' directory

Please write a regression test for what you're fixing. Even if it
seems trivial or obvious, try to add a test that will prevent
regressions.

If your change is minor, feel free to piggyback on already-written
tests, possibly just adding a small step to a similar existing test.
Every second counts in CI.

If your commit really, truly does not need tests, you can proceed
by asking a repo maintainer to set the '$OVERRIDE_LABEL' github label.
This will only be done when there's no reasonable alternative.
EOF

exit 1
