// Code generated by go generate; DO NOT EDIT.
package secrets

import (
	"net/url"

	"github.com/containers/podman/v5/pkg/bindings/internal/util"
)

// Changed returns true if named field has been set
func (o *InspectOptions) Changed(fieldName string) bool {
	return util.Changed(o, fieldName)
}

// ToParams formats struct fields to be passed to API service
func (o *InspectOptions) ToParams() (url.Values, error) {
	return util.ToParams(o)
}

// WithShowSecret set field ShowSecret to given value
func (o *InspectOptions) WithShowSecret(value bool) *InspectOptions {
	o.ShowSecret = &value
	return o
}

// GetShowSecret returns value of field ShowSecret
func (o *InspectOptions) GetShowSecret() bool {
	if o.ShowSecret == nil {
		var z bool
		return z
	}
	return *o.ShowSecret
}
