// +build  seccomp   ostree selinux  varlink exclude_graphdriver_devicemapper

// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  libpod

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( ContainerConfig ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ContainerConfig ) UnmarshalJSON([]byte) error { return nil }
func ( ContainerConfig ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ContainerConfig ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ContainerConfig *ContainerConfig

func ( ExecSession ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ExecSession ) UnmarshalJSON([]byte) error { return nil }
func ( ExecSession ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ExecSession ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ExecSession *ExecSession

func ( containerState ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* containerState ) UnmarshalJSON([]byte) error { return nil }
func ( containerState ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* containerState ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_containerState *containerState
