// Code generated by go generate; DO NOT EDIT.
package containers

import (
	"net/url"

	"github.com/containers/podman/v3/pkg/bindings/internal/util"
)

// Changed returns true if named field has been set
func (o *CheckpointOptions) Changed(fieldName string) bool {
	return util.Changed(o, fieldName)
}

// ToParams formats struct fields to be passed to API service
func (o *CheckpointOptions) ToParams() (url.Values, error) {
	return util.ToParams(o)
}

// WithExport set field Export to given value
func (o *CheckpointOptions) WithExport(value string) *CheckpointOptions {
	o.Export = &value
	return o
}

// GetExport returns value of field Export
func (o *CheckpointOptions) GetExport() string {
	if o.Export == nil {
		var z string
		return z
	}
	return *o.Export
}

// WithIgnoreRootfs set field IgnoreRootfs to given value
func (o *CheckpointOptions) WithIgnoreRootfs(value bool) *CheckpointOptions {
	o.IgnoreRootfs = &value
	return o
}

// GetIgnoreRootfs returns value of field IgnoreRootfs
func (o *CheckpointOptions) GetIgnoreRootfs() bool {
	if o.IgnoreRootfs == nil {
		var z bool
		return z
	}
	return *o.IgnoreRootfs
}

// WithKeep set field Keep to given value
func (o *CheckpointOptions) WithKeep(value bool) *CheckpointOptions {
	o.Keep = &value
	return o
}

// GetKeep returns value of field Keep
func (o *CheckpointOptions) GetKeep() bool {
	if o.Keep == nil {
		var z bool
		return z
	}
	return *o.Keep
}

// WithLeaveRunning set field LeaveRunning to given value
func (o *CheckpointOptions) WithLeaveRunning(value bool) *CheckpointOptions {
	o.LeaveRunning = &value
	return o
}

// GetLeaveRunning returns value of field LeaveRunning
func (o *CheckpointOptions) GetLeaveRunning() bool {
	if o.LeaveRunning == nil {
		var z bool
		return z
	}
	return *o.LeaveRunning
}

// WithTCPEstablished set field TCPEstablished to given value
func (o *CheckpointOptions) WithTCPEstablished(value bool) *CheckpointOptions {
	o.TCPEstablished = &value
	return o
}

// GetTCPEstablished returns value of field TCPEstablished
func (o *CheckpointOptions) GetTCPEstablished() bool {
	if o.TCPEstablished == nil {
		var z bool
		return z
	}
	return *o.TCPEstablished
}
