// Code generated by go generate; DO NOT EDIT.
package images

import (
	"net/url"

	"github.com/containers/podman/v4/pkg/bindings/internal/util"
)

// Changed returns true if named field has been set
func (o *ImportOptions) Changed(fieldName string) bool {
	return util.Changed(o, fieldName)
}

// ToParams formats struct fields to be passed to API service
func (o *ImportOptions) ToParams() (url.Values, error) {
	return util.ToParams(o)
}

// WithChanges set field Changes to given value
func (o *ImportOptions) WithChanges(value []string) *ImportOptions {
	o.Changes = &value
	return o
}

// GetChanges returns value of field Changes
func (o *ImportOptions) GetChanges() []string {
	if o.Changes == nil {
		var z []string
		return z
	}
	return *o.Changes
}

// WithMessage set field Message to given value
func (o *ImportOptions) WithMessage(value string) *ImportOptions {
	o.Message = &value
	return o
}

// GetMessage returns value of field Message
func (o *ImportOptions) GetMessage() string {
	if o.Message == nil {
		var z string
		return z
	}
	return *o.Message
}

// WithReference set field Reference to given value
func (o *ImportOptions) WithReference(value string) *ImportOptions {
	o.Reference = &value
	return o
}

// GetReference returns value of field Reference
func (o *ImportOptions) GetReference() string {
	if o.Reference == nil {
		var z string
		return z
	}
	return *o.Reference
}

// WithURL set field URL to given value
func (o *ImportOptions) WithURL(value string) *ImportOptions {
	o.URL = &value
	return o
}

// GetURL returns value of field URL
func (o *ImportOptions) GetURL() string {
	if o.URL == nil {
		var z string
		return z
	}
	return *o.URL
}
