// Code generated by go generate; DO NOT EDIT.
package images

import (
	"net/url"

	"github.com/containers/podman/v3/pkg/bindings/internal/util"
)

// Changed returns true if named field has been set
func (o *ResolveOptions) Changed(fieldName string) bool {
	return util.Changed(o, fieldName)
}

// ToParams formats struct fields to be passed to API service
func (o *ResolveOptions) ToParams() (url.Values, error) {
	return util.ToParams(o)
}

// WithPolicy set field Policy to given value
func (o *ResolveOptions) WithPolicy(value string) *ResolveOptions {
	o.Policy = &value
	return o
}

// GetPolicy returns value of field Policy
func (o *ResolveOptions) GetPolicy() string {
	if o.Policy == nil {
		var z string
		return z
	}
	return *o.Policy
}
