#!/bin/bash
# shellcheck disable=SC1091
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Main script to manage resources

# Print usage information
usage() {
    echo "Usage: $0 [--create-vol | --create-net | --create-cont | --cleanup-vol | --cleanup-net | --cleanup-cont | --list-procs | --list-vols | --list-nets]"
    exit 1
}

# Check if at least one argument is provided
if [ $# -lt 1 ]; then
    usage
fi

# Parse command-line arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --create-vol)
            shift
            ./volume create
	    exit $?
            ;;
        --create-net)
            shift
	    ./network create
	    exit $?
            ;;
        --create-cont)
            shift
            ./podman create
	    exit $?
            ;;
        --cleanup-vol)
            shift
            ./volume remove
	    exit $?
            ;;
        --cleanup-net)
            shift
            ./network remove
	    exit $?
            ;;
        --cleanup-cont)
            shift
            ./podman remove
	    exit $?
            ;;
        --list-procs)
            ./processes list
	    exit $?
            ;;
        --list-vols)
            ./volume list
	    exit $?
            ;;
        --list-nets)
            ./network list
	    exit $?
            ;;
        --is-enabled-service)
            ./systemd is-enabled
	    exit $?
            ;;
    esac
    shift
done
