#!/bin/bash -e
# shellcheck disable=SC1091
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
CONFIG_DIR="$HOME/.config/podman-stressor"
source "$CONFIG_DIR/constants"
source "$SHARE_DIR/common"

# Function to create a volume
create_volume() {
    if [[ "$VERBOSE" = "${FEATURE_ENABLED}" ]]; then
        echo -e "[ ${BLUE}INFO${NC} ] creating volume ${VOLUME_NAME}"
    fi

    if ! podman volume create "${VOLUME_NAME}" 1> /dev/null; then
	echo -e "[ ${RED}FAIL${NC} ] unable to create volume ${VOLUME_NAME}."
        exit 255
    fi
    if [[ "$VERBOSE" = "${FEATURE_ENABLED}" ]]; then
        echo -e "[ ${GREEN}PASS${NC} ] volume ${VOLUME_NAME} created."
    fi

}

# Function to remove a volume
remove_volume() {
    if [[ "$VERBOSE" = "${FEATURE_ENABLED}" ]]; then
        echo -e "[ ${BLUE}INFO${NC} ] removing volume ${VOLUME_NAME}"
    fi

    if ! podman volume rm "${VOLUME_NAME}" --force 1> /dev/null; then
	echo -e "[ ${RED}FAIL${NC} ] unable to remove volume ${VOLUME_NAME}"
        exit 255
    fi
    if [[ "$VERBOSE" = "${FEATURE_ENABLED}" ]]; then
        echo -e "[ ${GREEN}PASS${NC} ] volume ${VOLUME_NAME} removed."
    fi
}

# Function to list volumes
list_volumes() {
    echo
    # Print header
    # Print header
    echo -e "[ ${BLUE}INFO${NC} ] ==============================================="
    echo -e "[ ${BLUE}INFO${NC} ]              ${GREEN}Listing current podman volume${NC}"
    echo -e "[ ${BLUE}INFO${NC} ] ==============================================="

    # Execute podman volume ls and check for errors
    if ! output=$(podman volume ls 2>&1); then
        echo -e "[ ${RED}ERROR${NC} ] Failed to execute 'podman volume ls':"
        echo -e "[ ${RED}ERROR${NC} ] $output"
        echo -e "[ ${BLUE}INFO${NC} ] ==============================================="
        exit 1
    fi

    # Print the output line by line with the formatted header
    echo "$output" | while IFS= read -r line; do
        echo -e "[ ${BLUE}INFO${NC} ] $line"
    done

    # Print footer
    echo -e "[ ${BLUE}INFO${NC} ] ==============================================="
}

# Main function to run the script
main() {
    if [ $# -lt 1 ]; then
        echo "Usage: $0 <create|remove|list>"
        exit 1
    fi

    local action=$1

    case $action in
        create)
            create_volume
            ;;
        remove)
            remove_volume
            ;;
        list)
            list_volumes
            ;;
        *)
            echo "Unknown action: $action"
            exit 1
            ;;
    esac
}

main "$@"
