# This should get merged into fcos-podman-next-build.yml once ready
name: Build machine images with podman-next

on:
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: fcos
  # IMAGE_ARCHS has to be comma separated
  IMAGE_ARCHS: amd64, arm64
  IMAGE_REGISTRY: quay.io/podman
  COPR_OWNER: rhcontainerbot
  COPR_PROJECT: podman-next

jobs:
  fcos-podman-next-image-build:
    runs-on: ubuntu-latest

    steps:
    - name: Install qemu dependency
      run: |
        sudo apt update
        sudo apt -y install qemu-user-static podman

    - name: Set up cosa
      run:  |
        podman pull quay.io/coreos-assembler/coreos-assembler
        cat ./contrib/podman-next/fcos-podmanimage/cosa-alias >> ~/.bashrc
        cosa init https://github.com/coreos/fedora-coreos-config
    
    - name: Build vhdx and qcow2 images
      run: |
        cosa fetch
        cosa build

        #- name: Push to quay.io/podman/playground
